### ISSUE TITLE
Experimental syntax 'jsx' disabled by default

### ISSUE THREAD

**Issue by dharwardt** [arpitBhalla/rn-arc-slider#1]
I've added the library according to your readme, but i'm getting the following error:

`./node_modules/rn-arc-slider/dist/index.js
SyntaxError: D:\my-app\node_modules\rn-arc-slider\dist\index.js: Support for the experimental syntax 'jsx' isn't currently enabled (78:13)`

Full message is attached.
[logMsg.txt](https://github.com/arpitBhalla/rn-arc-slider/files/7192183/logMsg.txt)

Did I miss any steps?

**Comment by arpitBhalla** [comment]
Thanks for raising this issue, I will fix it soon ;)

**Comment by arpitBhalla** [comment]
@dharwardt Has been fixed, Please star this repo, if you like my work
